// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TruckManager.Infrastructure.Persistence;

#nullable disable

namespace TruckManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260524224234_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TruckManager.Domain.Aggregates.Trucks.Truck", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("StatusId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Trucks_TenantId_Code")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_Trucks_TenantId_StatusId")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Trucks", (string)null);
                });

            modelBuilder.Entity("TruckManager.Infrastructure.Persistence.Entities.TruckDomainEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId");

                    b.HasIndex("AggregateId", "AggregateVersion")
                        .HasDatabaseName("IX_TruckDomainEvents_AggregateId_AggregateVersion");

                    b.HasIndex("TenantId", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_TruckDomainEvents_TenantId_OccurredAtUtc");

                    b.ToTable("TruckDomainEvents", (string)null);
                });

            modelBuilder.Entity("TruckManager.Infrastructure.Persistence.Entities.TruckStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_TruckStatuses_Code");

                    b.ToTable("TruckStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "OUT_OF_SERVICE",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Out of Service",
                            Sequence = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "LOADING",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Loading",
                            Sequence = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "TO_JOB",
                            IsActive = true,
                            IsSystem = true,
                            Name = "To Job",
                            Sequence = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "AT_JOB",
                            IsActive = true,
                            IsSystem = true,
                            Name = "At Job",
                            Sequence = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "RETURNING",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Returning",
                            Sequence = 5
                        });
                });

            modelBuilder.Entity("TruckManager.Infrastructure.Persistence.Entities.TruckStatusTransition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("FromStatusId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("boolean");

                    b.Property<int>("ToStatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ToStatusId");

                    b.HasIndex("FromStatusId", "ToStatusId")
                        .IsUnique()
                        .HasDatabaseName("UX_TruckStatusTransitions_From_To");

                    b.ToTable("TruckStatusTransitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FromStatusId = 1,
                            IsAllowed = true,
                            ToStatusId = 2
                        },
                        new
                        {
                            Id = 2,
                            FromStatusId = 2,
                            IsAllowed = true,
                            ToStatusId = 1
                        },
                        new
                        {
                            Id = 3,
                            FromStatusId = 1,
                            IsAllowed = true,
                            ToStatusId = 3
                        },
                        new
                        {
                            Id = 4,
                            FromStatusId = 3,
                            IsAllowed = true,
                            ToStatusId = 1
                        },
                        new
                        {
                            Id = 5,
                            FromStatusId = 1,
                            IsAllowed = true,
                            ToStatusId = 4
                        },
                        new
                        {
                            Id = 6,
                            FromStatusId = 4,
                            IsAllowed = true,
                            ToStatusId = 1
                        },
                        new
                        {
                            Id = 7,
                            FromStatusId = 1,
                            IsAllowed = true,
                            ToStatusId = 5
                        },
                        new
                        {
                            Id = 8,
                            FromStatusId = 5,
                            IsAllowed = true,
                            ToStatusId = 1
                        },
                        new
                        {
                            Id = 9,
                            FromStatusId = 2,
                            IsAllowed = true,
                            ToStatusId = 3
                        },
                        new
                        {
                            Id = 10,
                            FromStatusId = 3,
                            IsAllowed = true,
                            ToStatusId = 4
                        },
                        new
                        {
                            Id = 11,
                            FromStatusId = 4,
                            IsAllowed = true,
                            ToStatusId = 5
                        },
                        new
                        {
                            Id = 12,
                            FromStatusId = 5,
                            IsAllowed = true,
                            ToStatusId = 2
                        });
                });

            modelBuilder.Entity("TruckManager.Domain.Aggregates.Trucks.Truck", b =>
                {
                    b.OwnsOne("TruckManager.Domain.ValueObjects.ConcurrencyStamp", "ConcurrencyStamp", b1 =>
                        {
                            b1.Property<Guid>("TruckId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("LastModifiedUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastModifiedUtc");

                            b1.Property<long>("Version")
                                .IsConcurrencyToken()
                                .HasColumnType("bigint")
                                .HasColumnName("Version");

                            b1.HasKey("TruckId");

                            b1.ToTable("Trucks");

                            b1.WithOwner()
                                .HasForeignKey("TruckId");
                        });

                    b.Navigation("ConcurrencyStamp")
                        .IsRequired();
                });

            modelBuilder.Entity("TruckManager.Infrastructure.Persistence.Entities.TruckStatusTransition", b =>
                {
                    b.HasOne("TruckManager.Infrastructure.Persistence.Entities.TruckStatus", null)
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TruckStatusTransitions_TruckStatuses_FromStatusId");

                    b.HasOne("TruckManager.Infrastructure.Persistence.Entities.TruckStatus", null)
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TruckStatusTransitions_TruckStatuses_ToStatusId");
                });
#pragma warning restore 612, 618
        }
    }
}
